Support copying bookmark url
flexibeast/ebuku pull request #19
Opened 2021-09-30 04:10 UTC by junjizhi

This would be useful if we want to use the URL somewhere, e.g., in a markdown or org file.

2021-09-30 11:28 UTC, flexibeast requested changes

2021-09-30 11:28 UTC, flexibeast commented on README.md
> +* <kbd>C</kbd> - Copy the bookmark at point to kill ring (`ebuku-copy-url`).
The README is generated from the source by using `el2markdown`, so just remove this change.

2021-09-30 11:28 UTC, flexibeast commented on ebuku.el
> +;; * `C' - Add a new bookmark (`ebuku-copy-url').
Change to:
> Copy the URL of the bookmark at point to the kill ring

2021-09-30 11:28 UTC, flexibeast commented on ebuku.el
> +  "Copy the URL to kill ring for the bookmark at point."
Change docstring to:
> Copy the URL of the bookmark at point to the kill ring.

2021-09-30 11:28 UTC, flexibeast commented
This is great - thanks! i've left a few comments on the PR itself, but also, please add `(require 'browse-url)` before the "User-customisable settings" section, as otherwise `browse-url-url-at-point` is not available. Once you've made all the changes, i'll be happy to merge. :-)

2021-09-30 13:31 UTC, junjizhi commented
@flexibeast My bad. Your comments have been addressed!

2021-10-01 02:39 UTC, merged

2021-10-01 02:39 UTC, flexibeast commented
Merged, thanks!